# Lesson 09 demo: Numpy

## 1. Set up

To install numpy:

```text
pip install numpy
```

In [2]:
import numpy as np

In [3]:
print(f"Numpy version: {np.__version__}")

Numpy version: 1.23.5


## 2. Creating array

### 2.1. From a list

In [5]:
my_arr = np.array([1, 2, 3, 4, 5])
type(my_arr)

numpy.ndarray

In [6]:
my_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(my_arr)

[[1 2 3]
 [4 5 6]]


### 2.2. Using built-functions

In [9]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
constant_array = np.full((3,4), 1.0)
print(constant_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 3. Array attributes

In [12]:
constant_array.shape

(3, 4)

In [13]:
constant_array.dtype

dtype('float64')

In [14]:
constant_array.nbytes

96

## 4. Array functions & operations

### 4.1. Arithmetic operations

In [16]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = np.array([1])

In [17]:
print(a + b)

[11 22 33 44]


In [20]:
a_list = [10,20,30,40]
b_list = [1,2,3,4]

In [21]:
print(a_list + b_list)

[10, 20, 30, 40, 1, 2, 3, 4]


### 4.2 Statistical methods

In [22]:
print(np.mean(a))

25.0


In [23]:
print(np.sum(a))

100


### 4.3. Methods on axes

In [31]:
arr_2d = np.array([[
    [10,20,30,40],
    [1,2,3,4],
],[
    [1,2,3,4],
    [3,4,5,6]
]])

print(arr_2d)

[[[10 20 30 40]
  [ 1  2  3  4]]

 [[ 1  2  3  4]
  [ 3  4  5  6]]]


In [33]:
arr_2d.shape

(2, 2, 4)

In [32]:
print(np.mean(arr_2d))

8.625


In [34]:
print(np.mean(arr_2d, axis=0))

[[ 5.5 11.  16.5 22. ]
 [ 2.   3.   4.   5. ]]


In [35]:
print(np.mean(arr_2d, axis=1))

[[ 5.5 11.  16.5 22. ]
 [ 2.   3.   4.   5. ]]


In [36]:
arr_2d.shape

(2, 2, 4)

### 4.4. Shape manipulation

In [37]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
new_arr = arr.reshape(2,6)
print(new_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [39]:
new_arr = arr.reshape(2,7)
print(new_arr)

ValueError: cannot reshape array of size 12 into shape (2,7)